### ISSUE TITLE
Connected app, but posts not showing up

### ISSUE THREAD

**Issue by alexanderpepper** [xavizalote/telescope-slack#3]
First I want to thank you for creating this plugin. It's exactly what my team needs right now.

I've created an app, added it to my team's channel with the 'Add to Slack' button, and I'm getting a 'Successfully Connected' message, but none of the posts I add are presented in the channel.

I'm not running my telescope site over SSL yet. Do you think that might have something to do with it?

**Comment by alexanderpepper** [comment]
ver 0.0.9 fixed the issue.

You da man Xavier!

**Comment by xavxyz** [comment]
Hey @alexanderpepper, so happy that it worked for you! The problem may have been when I tried the postApproved callback!

Sorry that I didn't see your issue earlier! Keep opening issue if you see something weird happening, or pr if you want to improve the package :+1: :)

**Comment by xavxyz** [comment]
@alexanderpepper there is an update! You should use now `xavcz:slackscope` and no more `xavizalote:telescope-slack` if you want to stay tuned :dancers:

**Comment by alexanderpepper** [comment]
Thanks for letting me know @xavcz! I'll make the switch.
